services:
  tagim.api:
    image: tagim.api
    build:
      context: .
      dockerfile: Tagim.Api/Dockerfile
    container_name: tagim_api
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=TagimDb;User Id=postgres;Password=admin;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./Tagim.Api/wwwroot/uploads:/app/wwwroot/uploads
    networks:
      - elastic

  db:
    image: postgres:16
    container_name: tagim_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=TagimDb
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - elastic
        
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.4.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false 
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - elastic
    
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:9.4.0
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elastic
  
networks:
  elastic:
    driver: bridge

volumes:
  postgres_data:
  elasticsearch-data: